-- Textos da interface em PT-BR e EN (o audio continua sempre em ingles).
-- Uso: L:t('ui.fuel') | legendas fixas via L:cap(textoPT).

local Lang = {}
Lang.__index = Lang

local STRINGS = {
  ['pt-BR'] = {
    ['app.name'] = 'AC Engineer Sally',
    ['dash.title'] = 'SALLY - CENTRAL DE CORRIDA',
    ['dash.subtitle'] = 'ENGENHEIRA DE CORRIDA  ·  TELEMETRIA AO VIVO',
    ['dash.poslap'] = 'P%s  |  Volta %d%s',
    ['dash.lap'] = 'Volta %d%s',
    ['dash.clock'] = 'Relógio: %d:%02d restantes',
    ['dash.live'] = 'SESSÃO AO VIVO',
    ['dash.waiting'] = 'AGUARDANDO SESSÃO',
    ['dash.paused'] = 'SIMULAÇÃO PAUSADA',
    ['dash.replay'] = 'REPLAY',
    ['dash.finished'] = 'SESSÃO FINALIZADA',
    ['dash.radio_live'] = 'Sally pode falar durante a corrida',
    ['dash.radio_paused'] = 'Rádio pausado — sem avisos de voz',
    ['dash.strategy'] = 'ESTRATÉGIA & COMBUSTÍVEL',
    ['dash.stint'] = 'Stint atual: ',
    ['dash.vehicle'] = 'ESTADO DO CARRO',
    ['dash.damage'] = 'DANO REGISTRADO',
    ['dash.hit'] = 'Batida: +%.1f | queda %.0f km/h',
    ['dash.hit_none'] = 'Sem batida recente',
    ['dash.penalty'] = 'PENALIDADE',
    ['dash.penalty_detail'] = 'Estado reportado pelo CSP',
    ['dash.penalty_na'] = 'Indisponível',
    ['dash.penalty_none'] = 'Sem penalidade',
    ['dash.penalty_pits'] = 'Parada obrigatória',
    ['dash.penalty_pits_laps'] = 'Parada obrigatória: em até %d voltas',
    ['dash.penalty_return'] = 'Retorno aos boxes',
    ['dash.penalty_pit_wait'] = 'Aguarde nos boxes',
    ['dash.penalty_wait_time'] = 'Aguarde nos boxes: %d s',
    ['dash.penalty_slow'] = 'Reduza a velocidade',
    ['dash.penalty_slow_time'] = 'Reduza a velocidade por %d s',
    ['dash.penalty_black'] = 'Bandeira preta',
    ['dash.penalty_cleared'] = 'Penalidade liberada',
    ['dash.penalty_unknown'] = 'Penalidade ativa',
    ['spot.free'] = 'PISTA LIVRE',
    ['spot.off'] = 'SPOTTER DESLIGADO',
    ['spot.wait'] = 'SPOTTER EM ESPERA',
    ['spot.both'] = 'DOS DOIS LADOS - SEGURA',
    ['spot.left'] = 'CARRO A ESQUERDA',
    ['spot.right'] = 'CARRO A DIREITA',
    ['radio.on'] = 'Ligar rádio',
    ['radio.off'] = 'Pausar rádio',
    ['radio.paused_short'] = 'PAUSADO',
    ['radio.now_on'] = 'Rádio ligado.',
    ['radio.now_off'] = 'Rádio pausado.',
    ['card.fuel'] = 'COMBUSTÍVEL',
    ['card.range'] = 'AUTONOMIA',
    ['card.margin_ok'] = 'Margem ok',
    ['card.margin'] = 'Margem: %.1f L',
    ['card.short'] = 'Faltam %.1f L',
    ['card.remaining'] = 'RESTAM',
    ['card.timed'] = 'cronometrada',
    ['card.bylaps'] = 'por voltas',
    ['card.lastbest'] = 'ÚLTIMA / MELHOR',
    ['card.best'] = 'Melhor: ',
    ['tyres.title'] = 'PNEUS',
    ['tyre.fl'] = 'D.ESQ',
    ['tyre.fr'] = 'D.DIR',
    ['tyre.rl'] = 'T.ESQ',
    ['tyre.rr'] = 'T.DIR',
    ['tyres.compound'] = 'Composto: ',
    ['tyres.ers'] = 'ERS: ',
    ['history.title'] = 'HISTÓRICO DO RÁDIO',
    ['history.empty'] = 'As falas aparecem aqui.',
    ['set.voice_ready'] = 'Voz Sally pronta.',
    ['set.voice_missing'] = 'Pasta audio/sally não encontrada!',
    ['set.section_radio'] = 'RÁDIO & MIXAGEM',
    ['set.section_alerts'] = 'AVISOS AUTOMÁTICOS',
    ['set.tests_note'] = 'Testes tocam na hora',
    ['set.avatar'] = 'Mostrar Sally 2D no rádio',
    ['set.avatar_preview'] = 'Prévia das expressões',
    ['avatar.neutral'] = 'Neutra',
    ['avatar.angry'] = 'Brava',
    ['avatar.focused'] = 'Focada',
    ['avatar.concerned'] = 'Alerta',
    ['avatar.happy'] = 'Feliz',
    ['avatar.furious'] = 'Furiosa',
    ['avatar.sarcastic'] = 'Sarcástica',
    ['avatar.surprised'] = 'Surpresa',
    ['avatar.relieved'] = 'Aliviada',
    ['avatar.determined'] = 'Determinada',
    ['avatar.alert'] = 'Atenta',
    ['avatar.celebrating'] = 'Comemorando',
    ['avatar.confused'] = 'Confusa',
    ['avatar.disappointed'] = 'Decepcionada',
    ['set.commentary_section'] = 'COMENTÁRIOS DE CORRIDA',
    ['set.commentary_enabled'] = 'Comentários automáticos por telemetria',
    ['set.commentary_note'] = 'Sally escolhe falas gravadas por regras locais após voltas válidas no treino, qualificação ou corrida, usando ritmo e posição. Sem IA online, chave ou envio de dados.',
    ['set.eng'] = 'Engenheira: %.0f%%',
    ['set.spot'] = 'Spotter: %.0f%%',
    ['set.bg'] = 'Chiado: %.2f',
    ['set.speed'] = 'Velocidade: %.2fx',
    ['set.pitch'] = 'Tom: %.2fx',
    ['set.spoton'] = 'Spotter ligado',
    ['set.beep'] = 'Bip do rádio',
    ['set.wflags'] = 'Avisos: bandeiras',
    ['set.wfuel'] = 'Avisos: combustível',
    ['set.wtyres'] = 'Avisos: pneus',
    ['set.wdamage'] = 'Avisos: danos',
    ['set.wsummary'] = 'Informes automaticos por volta',
    ['set.every'] = 'Informe a cada %.0f volta(s)',
    ['set.fuelsec'] = 'Combustível a cada %.0f s',
    ['set.rants'] = 'Xingamentos: %.0f (0=desligado, 3=frequente)',
    ['set.reserve'] = 'Reserva: %.2f voltas',
    ['set.tests'] = 'TESTES (ouvido na hora)',
    ['set.t_radio'] = 'Radio check',
    ['set.t_penalty'] = 'Ler penalidade do jogo',
    ['set.t_left'] = 'Spotter: car left',
    ['set.t_clear'] = 'Spotter: all clear',
    ['set.t_seq'] = 'Sequência do spotter',
    ['set.t_clearq'] = 'Limpar fila',
    ['set.catalog'] = 'CATÁLOGO SALLY',
    ['set.nocat'] = 'Nenhum áudio encontrado.',
    ['set.folder'] = 'Pasta: ',
    ['set.phrase'] = 'Frase: ',
    ['set.play'] = 'Tocar',
    ['set.random'] = 'Aleatória',
    ['set.spotst'] = 'Spotter: ',
    ['set.active'] = 'ATIVO',
    ['set.standby'] = 'espera',
    ['set.last'] = 'Última: ',
    ['set.telemetry'] = 'TELEMETRIA AO VIVO',
    ['set.t_fuel'] = 'Combustivel: ',
    ['set.t_cons'] = ' | consumo: ',
    ['set.t_dmg'] = 'Dano: ',
    ['set.t_pen'] = ' | penalidade CSP: ',
    ['set.t_na'] = 'indisponivel',
    ['set.t_hit'] = 'Ultima batida: dano +%.1f | queda %.0f km/h',
    ['set.clips'] = 'Clips: ',
    ['set.clips2'] = ' frases no catalogo',
    ['set.lang'] = 'Idioma / Language:',
    ['msg.radio_replay'] = 'Ligue o rádio e saia do replay.',
    ['msg.no_voice'] = 'Voz Sally indisponível.',
    ['msg.no_data'] = 'Entre na pista para telemetria ao vivo.',
    ['msg.spot'] = 'Spotter: ',
    ['msg.playing'] = 'Tocando: ',
    ['msg.testradio'] = 'Teste: radio check',
    ['unit.lap'] = 'Volta',
    ['unit.laps'] = 'voltas',
    ['unit.laps1'] = '%.1f voltas',
    ['unit.laps0'] = '%.0f voltas',
    ['unit.fuel_l'] = '%.1f L',
    ['unit.cons'] = '%.2f L/volta (%d)',
    ['unit.cons_short'] = '%.2f L/volta',
    ['unit.cons_wait'] = 'Complete voltas limpas',
    ['unit.temp'] = '%.0f C',
    ['unit.psi'] = '%.1f psi',
    ['unit.laptime'] = '%d:%02d.%03d',
  },
  ['en-US'] = {
    ['app.name'] = 'AC Engineer Sally',
    ['dash.title'] = 'SALLY - RACE HUB',
    ['dash.subtitle'] = 'RACE ENGINEER  ·  LIVE TELEMETRY',
    ['dash.poslap'] = 'P%s  |  Lap %d%s',
    ['dash.lap'] = 'Lap %d%s',
    ['dash.clock'] = 'Clock: %d:%02d left',
    ['dash.live'] = 'SESSION LIVE',
    ['dash.waiting'] = 'WAITING FOR SESSION',
    ['dash.paused'] = 'SIMULATION PAUSED',
    ['dash.replay'] = 'REPLAY',
    ['dash.finished'] = 'SESSION FINISHED',
    ['dash.radio_live'] = 'Sally can speak during the race',
    ['dash.radio_paused'] = 'Radio paused — no voice calls',
    ['dash.strategy'] = 'FUEL & STRATEGY',
    ['dash.stint'] = 'Current stint: ',
    ['dash.vehicle'] = 'CAR STATUS',
    ['dash.damage'] = 'RECORDED DAMAGE',
    ['dash.hit'] = 'Impact: +%.1f | speed drop %.0f kph',
    ['dash.hit_none'] = 'No recent impact',
    ['dash.penalty'] = 'PENALTY',
    ['dash.penalty_detail'] = 'Status reported by CSP',
    ['dash.penalty_na'] = 'Unavailable',
    ['dash.penalty_none'] = 'No penalty',
    ['dash.penalty_pits'] = 'Mandatory pit stop',
    ['dash.penalty_pits_laps'] = 'Mandatory pit stop within %d laps',
    ['dash.penalty_return'] = 'Return to pits',
    ['dash.penalty_pit_wait'] = 'Wait in the pits',
    ['dash.penalty_wait_time'] = 'Wait in the pits: %d s',
    ['dash.penalty_slow'] = 'Slow down',
    ['dash.penalty_slow_time'] = 'Slow down for %d s',
    ['dash.penalty_black'] = 'Black flag',
    ['dash.penalty_cleared'] = 'Penalty cleared',
    ['dash.penalty_unknown'] = 'Penalty active',
    ['spot.free'] = 'TRACK CLEAR',
    ['spot.off'] = 'SPOTTER OFF',
    ['spot.wait'] = 'SPOTTER STANDBY',
    ['spot.both'] = 'BOTH SIDES - HOLD ON',
    ['spot.left'] = 'CAR LEFT',
    ['spot.right'] = 'CAR RIGHT',
    ['radio.on'] = 'Radio on',
    ['radio.off'] = 'Pause radio',
    ['radio.paused_short'] = 'PAUSED',
    ['radio.now_on'] = 'Radio on.',
    ['radio.now_off'] = 'Radio paused.',
    ['card.fuel'] = 'FUEL',
    ['card.range'] = 'RANGE',
    ['card.margin_ok'] = 'Margin ok',
    ['card.margin'] = 'Margin: %.1f L',
    ['card.short'] = 'Short %.1f L',
    ['card.remaining'] = 'TO GO',
    ['card.timed'] = 'timed',
    ['card.bylaps'] = 'by laps',
    ['card.lastbest'] = 'LAST / BEST',
    ['card.best'] = 'Best: ',
    ['tyres.title'] = 'TYRES',
    ['tyre.fl'] = 'FL',
    ['tyre.fr'] = 'FR',
    ['tyre.rl'] = 'RL',
    ['tyre.rr'] = 'RR',
    ['tyres.compound'] = 'Compound: ',
    ['tyres.ers'] = 'ERS: ',
    ['history.title'] = 'RADIO HISTORY',
    ['history.empty'] = 'Calls will show up here.',
    ['set.voice_ready'] = 'Sally voice ready.',
    ['set.voice_missing'] = 'audio/sally folder missing!',
    ['set.section_radio'] = 'RADIO & MIX',
    ['set.section_alerts'] = 'AUTOMATIC WARNINGS',
    ['set.tests_note'] = 'Tests play immediately',
    ['set.avatar'] = 'Show 2D Sally on radio',
    ['set.avatar_preview'] = 'Expression preview',
    ['avatar.neutral'] = 'Neutral',
    ['avatar.angry'] = 'Angry',
    ['avatar.focused'] = 'Focused',
    ['avatar.concerned'] = 'Concerned',
    ['avatar.happy'] = 'Happy',
    ['avatar.furious'] = 'Furious',
    ['avatar.sarcastic'] = 'Sarcastic',
    ['avatar.surprised'] = 'Surprised',
    ['avatar.relieved'] = 'Relieved',
    ['avatar.determined'] = 'Determined',
    ['avatar.alert'] = 'Alert',
    ['avatar.celebrating'] = 'Celebrating',
    ['avatar.confused'] = 'Confused',
    ['avatar.disappointed'] = 'Disappointed',
    ['set.commentary_section'] = 'RACE COMMENTARY',
    ['set.commentary_enabled'] = 'Automatic telemetry commentary',
    ['set.commentary_note'] = 'Sally selects prerecorded lines with local rules after valid laps in practice, qualifying or race, using pace and position. No online AI, API key or data sharing.',
    ['set.eng'] = 'Engineer: %.0f%%',
    ['set.spot'] = 'Spotter: %.0f%%',
    ['set.bg'] = 'Static: %.2f',
    ['set.speed'] = 'Speed: %.2fx',
    ['set.pitch'] = 'Pitch: %.2fx',
    ['set.spoton'] = 'Spotter on',
    ['set.beep'] = 'Radio beep',
    ['set.wflags'] = 'Warnings: flags',
    ['set.wfuel'] = 'Warnings: fuel',
    ['set.wtyres'] = 'Warnings: tyres',
    ['set.wdamage'] = 'Warnings: damage',
    ['set.wsummary'] = 'Automatic lap briefs',
    ['set.every'] = 'Brief every %.0f lap(s)',
    ['set.fuelsec'] = 'Fuel every %.0f s',
    ['set.rants'] = 'Swearing: %.0f (0=off, 3=often)',
    ['set.reserve'] = 'Reserve: %.2f laps',
    ['set.tests'] = 'TESTS (audible now)',
    ['set.t_radio'] = 'Radio check',
    ['set.t_penalty'] = 'Read game penalty',
    ['set.t_left'] = 'Spotter: car left',
    ['set.t_clear'] = 'Spotter: all clear',
    ['set.t_seq'] = 'Spotter sequence',
    ['set.t_clearq'] = 'Clear queue',
    ['set.catalog'] = 'SALLY CATALOG',
    ['set.nocat'] = 'No audio found.',
    ['set.folder'] = 'Folder: ',
    ['set.phrase'] = 'Phrase: ',
    ['set.play'] = 'Play',
    ['set.random'] = 'Random',
    ['set.spotst'] = 'Spotter: ',
    ['set.active'] = 'ACTIVE',
    ['set.standby'] = 'standby',
    ['set.last'] = 'Last: ',
    ['set.telemetry'] = 'LIVE TELEMETRY',
    ['set.t_fuel'] = 'Fuel: ',
    ['set.t_cons'] = ' | cons: ',
    ['set.t_dmg'] = 'Damage: ',
    ['set.t_pen'] = ' | CSP penalty: ',
    ['set.t_na'] = 'unavailable',
    ['set.t_hit'] = 'Last hit: dmg +%.1f | drop %.0f kph',
    ['set.clips'] = 'Clips: ',
    ['set.clips2'] = ' phrases in catalog',
    ['set.lang'] = 'Idioma / Language:',
    ['msg.radio_replay'] = 'Turn radio on and exit replay.',
    ['msg.no_voice'] = 'Sally voice unavailable.',
    ['msg.no_data'] = 'Go on track for live telemetry.',
    ['msg.spot'] = 'Spotter: ',
    ['msg.playing'] = 'Playing: ',
    ['msg.testradio'] = 'Test: radio check',
    ['unit.lap'] = 'Lap',
    ['unit.laps'] = 'laps',
    ['unit.laps1'] = '%.1f laps',
    ['unit.laps0'] = '%.0f laps',
    ['unit.fuel_l'] = '%.1f L',
    ['unit.cons'] = '%.2f L/lap (%d)',
    ['unit.cons_short'] = '%.2f L/lap',
    ['unit.cons_wait'] = 'Complete clean laps',
    ['unit.temp'] = '%.0f C',
    ['unit.psi'] = '%.1f psi',
    ['unit.laptime'] = '%d:%02d.%03d',
  },
}

-- Legendas PT -> EN (display). Exatas primeiro, depois padrões p/ dinâmicas.
-- Números puros passam direto.
local CAP_EN = {
  ['Estimamos'] = 'We estimate',
  ['litros restantes'] = 'liters left',
  ['voltas de autonomia'] = 'laps of range',
  ['voltas de combustível'] = 'laps of fuel',
  ['voltas com estes pneus'] = 'laps on these tyres',
  ['Sem dados'] = 'No data',
  ['Sem intervalo'] = 'No gap',
  ['Gap à frente'] = 'Gap ahead',
  ['Gap atrás'] = 'Gap behind',
  ['segundos'] = 'seconds',
  ['minutos'] = 'minutes',
  ['metros'] = 'metres',
  ['litros'] = 'liters',
  ['voltas'] = 'laps',
  ['graus'] = 'degrees',
  ['psi'] = 'psi',
  ['s'] = 's',
  ['P1'] = 'P1',
  ['P1, líder'] = 'P1, leader',
  ['P1, na liderança'] = 'P1, leading',
  ['Pole!'] = 'Pole!',
  ['Último'] = 'Last',
  ['Sem posição'] = 'No position',
  ['Melhor volta'] = 'Best lap',
  ['Melhor volta!'] = 'Best lap!',
  ['Última volta'] = 'Last lap',
  ['Última, líder!'] = 'Last lap, leader!',
  ['Última, pódio!'] = 'Last lap, podium!',
  ['Sua melhor'] = 'Your best',
  ['Boa volta'] = 'Good lap',
  ['Sem volta'] = 'No lap',
  ['Setores'] = 'Sectors',
  ['Sem setores'] = 'No sectors',
  ['Ritmo melhorando'] = 'Pace improving',
  ['Ritmo caindo'] = 'Pace dropping',
  ['Ritmo estável'] = 'Pace steady',
  ['Ritmo consistente'] = 'Consistent pace',
  ['Sem ritmo'] = 'No pace',
  ['Sem pneus'] = 'No tyres',
  ['Pneu quente'] = 'Hot tyre',
  ['Pressão'] = 'Pressure',
  ['Pressão alta'] = 'High pressure',
  ['Pressão baixa'] = 'Low pressure',
  ['Pneus frios'] = 'Cold tyres',
  ['Dianteiros frios'] = 'Cold fronts',
  ['Traseiros frios'] = 'Cold rears',
  ['Pneus gastos!'] = 'Worn tyres!',
  ['Desgaste'] = 'Wear',
  ['Desgaste leve'] = 'Light wear',
  ['Dano detectado'] = 'Damage',
  ['Dano grave'] = 'Heavy damage',
  ['Dano leve'] = 'Light damage',
  ['Só um toque'] = 'Just a touch',
  ['Sem dano'] = 'No damage',
  ['Suspensão'] = 'Suspension',
  ['Suspensão grave'] = 'Heavy suspension damage',
  ['Câmbio!'] = 'Gearbox!',
  ['Câmbio quebrou!'] = 'Gearbox broken!',
  ['Falha de motor'] = 'Engine failure',
  ['Motor ok'] = 'Engine ok',
  ['Motor quebrou'] = 'Engine failed',
  ['Motor quebrou!'] = 'Engine failed!',
  ['Sem clima'] = 'No weather',
  ['Ar'] = 'Air',
  ['Pista'] = 'Track',
  ['Pista livre'] = 'Track clear',
  ['Chovendo'] = 'Raining',
  ['Começou a chover!'] = 'Started raining!',
  ['Parou de chover'] = 'Stopped raining',
  ['MUITA chuva!'] = 'Heavy rain!',
  ['Box agora'] = 'Box now',
  ['Box pedido'] = 'Box requested',
  ['No box'] = 'In pits',
  ['Combustível ok'] = 'Fuel ok',
  ['Meio tanque'] = 'Half tank',
  ['Meio, economize'] = 'Half, save fuel',
  ['Meio, ok'] = 'Half, ok',
  ['Fim'] = 'End',
  ['Metade'] = 'Halfway',
  ['Largada!'] = 'Start!',
  ['Largada ok'] = 'Start ok',
  ['Largada ruim'] = 'Bad start',
  ['Largada péssima'] = 'Terrible start',
  ['Boa largada!'] = 'Good start!',
  ['Aguarde'] = 'Stand by',
  ['Voltas restantes'] = 'Laps left',
  ['Tempo restante'] = 'Time left',
  ['Push, keep pushing'] = 'Push!',
  ['Ataca!'] = 'Push!',
  ['Pela vitória!'] = 'For the win!',
  ['Pelo P2!'] = 'For P2!',
  ['Segura!'] = 'Hold on!',
  ['Radio check'] = 'Radio check',
  ['Radio check Sally'] = 'Radio check',
  ['Ok'] = 'Ok',
  ['Não entendi'] = 'Did not understand',
  ['Sem telemetria'] = 'No telemetry',
  ['Bandeira amarela'] = 'Yellow flag',
  ['Bandeira azul'] = 'Blue flag',
  ['Bandeira laranja'] = 'Orange flag',
  ['Bandeira preta'] = 'Black flag',
  ['Batalha!'] = 'Battle!',
  ['Bateria baixa'] = 'Battery low',
  ['Carro lento'] = 'Slow car',
  ['Carro parado!'] = 'Car stopped!',
  ['Combustivel acabando'] = 'Fuel running out',
  ['Combustivel apertado'] = 'Fuel tight',
  ['Combustivel restante'] = 'Fuel left',
  ['Corta!'] = 'Cut warning!',
  ['Vai faltar'] = 'Will be short',
  ['Vamos abastecer'] = 'We will refuel',
  ['Faltam'] = 'Short',
  ['Há uma penalidade'] = 'There is a penalty',
  ['Parada obrigatória'] = 'Mandatory stop',
  ['Penalidade cumprida'] = 'Penalty served',
  ['Penalidade pendente'] = 'Penalty pending',
  ['Penalidade: reduza'] = 'Penalty: slow down',
  ['Reduza para cumprir a penalidade'] = 'Slow down to serve',
  ['Ignorou azul'] = 'Ignored blue',
  ['Excesso no box'] = 'Speeding in pits',
  ['Queima de largada'] = 'Jump start',
  ['Drive-through'] = 'Drive-through',
  ['Achar 1s'] = 'Find 1s',
  ['Décimos'] = 'Tenths',
  ['Um décimo'] = 'One tenth',
  ['Melhora!'] = 'Improve!',
  ['Melhorando'] = 'Improving',
  ['Limitador!'] = 'Limiter!',
  ['Perdeu posição'] = 'Lost position',
  ['Duas de uma vez!'] = 'Two at once!',
  ['Ultrapassagem!'] = 'Overtake!',
  ['Pressionado'] = 'Under pressure',
  ['Pódio!'] = 'Podium!',
  ['Vitória!'] = 'Victory!',
  ['Voce esta bem?'] = 'Are you ok?',
  ['Voce tem penalidade'] = 'You have a penalty',
  ['Volta invalidada'] = 'Lap invalidated',
  ['De novo?!'] = 'Again?!',
  ['Ritmo piorando'] = 'Pace dropping',
  ['Rodou?'] = 'Spun?',
  ['Sally irritada'] = 'Angry Sally',
  ['Saída livre'] = 'Clear exit',
  ['Tráfego na saída'] = 'Traffic on exit',
  ['A parada custou'] = 'The stop cost',
  ['Sem ERS'] = 'No ERS',
  ['Sem consumo'] = 'No consumption',
  ['Sem dado de penalidade'] = 'No penalty data',
  ['Sally: penalidade indisponível'] = 'Sally: penalty unavailable',
  ['Sem disputa'] = 'No battle',
  ['Sem penalidade'] = 'No penalty',
  ['Sem ritmo'] = 'No pace',
  ['O líder'] = 'The leader',
  ['Atrás'] = 'Behind',
  ['À frente'] = 'Ahead',
  ['Pneu'] = 'Tyre',
  ['Óleo'] = 'Oil',
  ['Óleo quente'] = 'Hot oil',
  ['Água'] = 'Water',
  ['Água quente'] = 'Hot water',
  ['Última ativação'] = 'Last activation',
  ['Último push!'] = 'Last push!',
  ['Prepare-se'] = 'Get ready',
  ['mais frio dentro'] = 'colder inside',
  ['mais quente dentro'] = 'hotter inside',
  ['litros até o fim'] = 'liters to the end',
  ['litros por volta'] = 'liters per lap',
  ['por volta'] = 'per lap',
  ['faltam'] = 'left',
  ['Faltam'] = 'To go:',
  ['Autonomia'] = 'Range',
  ['Combustivel restante'] = 'Fuel left',
  ['por cento de bateria'] = 'percent battery',
  ['por cento de desgaste'] = 'percent wear',
  ['por volta'] = 'per lap',
  ['Track limits'] = 'Track limits',
  ['Carro à esquerda'] = 'Car left',
  ['Carro à direita'] = 'Car right',
  ['Ainda ao lado'] = 'Still there',
  ['Esquerda livre'] = 'Clear left',
  ['Direita livre'] = 'Clear right',
  ['Tudo livre'] = 'All clear',
  ['Três lado a lado'] = 'Three wide',
  ['Três, você à esquerda'] = 'Three wide left',
  ['Três, você à direita'] = 'Three wide right',
  ['Sally: MOTOR QUEBROU'] = 'Sally: ENGINE FAILED',
  ['Sally: sem ERS'] = 'Sally: no ERS',
  ['Sally: box?'] = 'Sally: box?',
  ['Sally: desabafo'] = 'Sally: rant',
  ['Sally: disputa'] = 'Sally: battle',
  ['Sally: dá para terminar'] = 'Sally: enough to finish',
  ['Sally: motor ok'] = 'Sally: engine ok',
  ['Sally: pneus'] = 'Sally: tyres',
  ['Sally: push'] = 'Sally: push',
  ['Sally: radio check'] = 'Sally: radio check',
  ['Sally: ritmo'] = 'Sally: pace',
  ['Sally: sem dados'] = 'Sally: no data',
  ['Sally: sem telemetria'] = 'Sally: no telemetry',
  ['Sally: sem posição'] = 'Sally: no position',
  ['Pneu furado, box!'] = 'Punctured tyre, box!',
  ['Sally: setores'] = 'Sally: sectors',
  ['Sally: ÚLTIMA VOLTA'] = 'Sally: LAST LAP',
}

-- Padrões p/ legendas dinâmicas (com números): ^ancorado, um %s por captura.
local CAP_PATTERNS = {
  { '^Setor (%d+)$', 'Sector %s' },
  { '^Setor (%d+) rápido$', 'Sector %s fast' },
  { '^Posicao P(%d+)$', 'Position P%s' },
  { '^P(%d+), na liderança$', 'P%s, leading' },
  { '^Sally: volta(.*)$', 'Sally: lap%1' },
  { '^Sally: gap ([%d.,]+) s(.*)$', 'Sally: gap %s s%s' },
  { '^Sally: P(%d+)$', 'Sally: P%s' },
  { '^Sally: dano total (%d+)$', 'Sally: total damage %s' },
  { '^Sally: bateria (.*)$', 'Sally: battery %1' },
  { '^Sally: motor ok (.*)$', 'Sally: engine ok %1' },
  { '^Sally: parar! Faltam ([%d.,]+) L$', 'Sally: stop! Short %s L' },
  { '^Sally: faltam ([%d.,]+) voltas$', 'Sally: %s laps left' },
  { '^Sally: penalidade (%d+)$', 'Sally: penalty %s' },
  { '^([%d.,]+) litros$', '%1 liters' },
  { '^([%d.,]+) segundos$', '%1 seconds' },
  { '^([%d.,]+) metros$', '%1 metres' },
  { '^([%d.,]+) minutos$', '%1 minutes' },
}

-- Último recurso: troca de palavras isoladas (só ASCII, sem risco).
local CAP_WORDS = {
  { 'voltas', 'laps' }, { 'volta', 'lap' }, { 'litros', 'liters' },
  { 'segundos', 'seconds' }, { 'graus', 'degrees' }, { 'minutos', 'minutes' },
  { 'metros', 'metres' }, { 'combustivel', 'fuel' }, { 'faltam', 'short' },
  { 'pneus', 'tyres' }, { 'ritmo', 'pace' }, { 'setores', 'sectors' },
  { 'disputa', 'battle' }, { 'desabafo', 'rant' }, { 'motor', 'engine' },
  { 'clima', 'weather' }, { 'dano', 'damage' }, { 'pista', 'track' },
  { 'posicao', 'position' },
}

function Lang.new(code)
  return setmetatable({ code = (code == 'en-US') and 'en-US' or 'pt-BR' }, Lang)
end

function Lang:t(key)
  local t = STRINGS[self.code] or STRINGS['pt-BR']
  local v = t[key]
  if v ~= nil then return v end
  return (STRINGS['pt-BR'])[key] or tostring(key)
end

function Lang:cap(text)
  if self.code ~= 'en-US' then return text end
  text = tostring(text)
  local exact = CAP_EN[text]
  if exact then return exact end
  for _, p in ipairs(CAP_PATTERNS) do
    local a, b = text:match(p[1])
    if a ~= nil then return string.format(p[2], a, b) end
  end
  for _, w in ipairs(CAP_WORDS) do
    text = text:gsub('%f[%a]' .. w[1] .. '%f[%A]', w[2])
  end
  return text
end

function Lang:set(code)
  self.code = (code == 'en-US') and 'en-US' or 'pt-BR'
end

return Lang
